apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ConfigMap.name }}
  namespace: {{ .Values.namespace }}
data:
  CARTS_BASE_URL: {{.Values.ConfigMap.data.CARTS_BASE_URL | quote }}
  CATALOGUE_IMAGES_BASE_URL: {{.Values.ConfigMap.data.CATALOGUE_IMAGES_BASE_URL | quote }}