apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "catalogue-db.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: init-db
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: {{ toJson .Values.command }}
          args: 
          {{- toYaml .Values.args | nindent 12 }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.volumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}
