apiVersion: v1
kind: Service
metadata:
  name: carts-db
  namespace: mogambo
  labels:
    app: carts-db
spec:
  selector:
    app: carts-db
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017