apiVersion: v1
kind: ConfigMap
metadata:
  name: front-end-config
  namespace: mogambo
data:
  CARTS_BASE_URL: "http://carts:8080"
  CATALOGUE_IMAGES_BASE_URL: "https://d3d1mcn975jivq.cloudfront.net"

