apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalogue.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "catalogue.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "catalogue.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "catalogue.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "catalogue.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "-port=80"
            - "-images=/images/"
            - "-DSN=$(CATALOGUE_DB_DSN)"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: {{  .Values.env.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.valueFrom.secretKeyRef.name }}
                  key: {{ .Values.env.valueFrom.secretKeyRef.key }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}